version: '3.0'

services:
  hacking-tools:
    build: hacking-tools
    ports:
      - 4040-4080:4040-4080
    environment:
        - USER_LOGIN=hacker
        - USER_PASS=hacker
    volumes:
      - ./hacking-tools-share:/home/hacker/share:rw
    privileged: true